### ISSUE TITLE
LCA - Data order

### ISSUE THREAD

**Issue by yuanjames** [Labo-Lacourse/stepmix#61] opened 2024-05-10 19:38 UTC
Hi,

I have recently conducted a series of experiments, I found it is tricky that the results changed when I shuffled the data (other settings same).

I am curious that LCA should have same results, but the shuffled data may change the convergence? am I right? If we want to have the same results, we may need to change parameters of LCA.

**Comment by sachaMorin** [comment] 2024-05-10 22:34
By other settings name, do you mean you’re shuffling the order of the variables?

Shuffling should not affect the fit quality of the overall model, but could affect the order of the parameters. It would be really helpful if you could provide a minimum example to reproduce what you observed, perhaps with one of the datasets in `stepmix.datasets`.

**Comment by yuanjames** [comment] 2024-05-10 22:54
Yes, agree with you, I think shuffling the data won't change the results. I just run the IRIS example, please check.

continuous_features = ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
                 'petal width (cm)']
continuous_data = df[continuous_features]

model = StepMix(n_components=3, measurement="continuous", verbose=1, random_state=123)

# Fit to data
model.fit(continuous_data)

# Save class membership predictions to df
df['continuous_pred'] = model.predict(continuous_data)

Then it gives me the results:

continuous_pred | 0 | 1 | 2
-- | -- | -- | --

50 | 0 | 0
0 | 43 | 7
0 | 2 | 48

On the other hand, I tried to shuffle the data, 
continuous_data_shuffled = continuous_data.sample(frac=1)
# Gaussian mixture model
model = StepMix(n_components=3, measurement="continuous", verbose=1, random_state=123)

# Fit to data
model.fit(continuous_data_shuffled)

# Save class membership predictions to df
df['continuous_pred'] = model.predict(continuous_data)

it shows a different crosstab result:

continuous_pred | 0 | 1 | 2
-- | -- | -- | --

0 | 50 | 0
7 | 0 | 43
48 | 0 | 2

**Comment by yuanjames** [comment] 2024-05-11 08:43
If my understanding is correct, I think if LCA can reach the convergence, then shuffling the data does not matter. However, if the LCA can't reach the convergence (related to the settings with LCA, for example, n_component), then shuffling did change the results.

I tried n_component = 2 or 3, shuffling did not change results, once I changed it to 5, as the above example shown, it changed the results. am I correct?

**Comment by sachaMorin** [comment] 2024-05-22 20:25
Looking at your previous results, the clusterings still look good. Each cluster captures a class (or a part of it if you have more clusters than classes).

It's also possible that this is caused by numerical issues. For example, the sum of an ndarray may actually vary slightly if you shuffle the elements due to the summing order.  See the following program:

```python
import numpy as np
np.random.seed(123)
a = np.random.random(100)
b = np.copy(a)
np.random.shuffle(b)
sum_a = np.sum(a)
sum_b = np.sum(b)
print(sum_a)
print(sum_b)
print(sum_a == sum_b)
```
Output:
```
50.14288800514812
50.142888005148116
False
```
Given the numerous sums and means taken in the StepMix estimation, those small differences can compound over time and could potentially explain what we're seeing here. I'm not sure and would be interested in seeing how other similar programs behave.

**Comment by sachaMorin** [comment] 2024-09-20 14:09
Closing. Feel free to reopen if you still want to discuss.

**Closed by sachaMorin** 2024-09-20 14:09 UTC
Labels: question
